---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/games":
    get:
      summary: List all games
      tags:
      - Games
      responses:
        '200':
          description: Games found
          content:
            application/json:
              schema:
                type: object
                properties:
                  games:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        status:
                          type: string
                      required:
                      - id
                      - status
                required:
                - games
    post:
      summary: Create a game
      tags:
      - Games
      parameters: []
      responses:
        '200':
          description: Game created
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  status:
                    type: string
                required:
                - id
                - status
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                seed:
                  type: string
                  example: 1234567890abcdef
                  description: Optional
  "/api/v1/games/{id}":
    get:
      summary: Show a game
      tags:
      - Games
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: Game found
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  status:
                    type: string
                required:
                - id
                - status
        '404':
          description: Game not found
  "/api/v1/games/{id}/roles/{role}":
    post:
      summary: Player chooses a role
      tags:
      - Games
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      - name: role
        in: path
        description: "Role to choose:\n * `builder` 建築師\n * `producer` 製造商\n * `trader`
          貿易商\n * `prospector` 礦工\n * `councillor` 議員\n "
        enum:
          builder: 建築師
          producer: 製造商
          trader: 貿易商
          prospector: 礦工
          councillor: 議員
        schema:
          type: string
          enum:
          - builder
          - producer
          - trader
          - prospector
          - councillor
        required: true
      - name: np
        in: query
        description: Automatically move game state to the next player
        schema:
          type: string
          example: '0'
        required: false
      responses:
        '200':
          description: Choose a role successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                required:
                - message
        '400':
          description: Game is already finished
        '422':
          description: Role is being taken
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: array
                    items:
                      type: string
                required:
                - error
  "/walking-skeleton":
    get:
      summary: Examine the walking skeleton
      tags:
      - Walking Skeleton
      responses:
        '200':
          description: Walk
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                required:
                - message
servers:
- url: http://localhost:3000
  description: Development environment
- url: https://ithome-ironman-2024-san-juan.zeabur.app/
  description: Production environment at Zeabur
